# conda env create --file environment.yml
# mamba env create --file environment.yml
name: notas_curso_est_inf_platzi
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - nbdime
  - numpy
  - pandas
  - pip
  - plotly
  - pyjanitor
  - pyprojroot
  - python=3.12
  - seaborn
  